#!/bin/bash
set -e

echo "Beginning installation of HephaestusFOAM application"

#==================================================================================================
#
#  Install hephaestusFoam
#
#==================================================================================================

cd hephaestusFoam
wmake > build.log
cd ../
echo "    HephaestusFOAM completed, view build.log for results"

#==================================================================================================
#
#  Install hephaestusRKFoam
#
#==================================================================================================

##cd hephaestusRKFoam
###wmake > build.log
##cd ../
##echo "    HephaestusRK.FOAM completed, view build.log for results"

