#!/bin/bash
set -e

##=================================================================================================
##
##  This script is for a clean installation of HephaestusFOAM onto OpenFOAM v12. If HephaestusFOAM
##  needs to be partially installed, one must currently install those specific modules in the 
##  installation order that appears in this script.
##
##  Note that OpenFOAM v12 must be completely installed.
##
##  Questions should be directed to matthew.holland@utsa.edu
##
##=================================================================================================

## Append hephaestusFOAM RC to bashrc
echo '. ~/hephaestusfoam/hephaestusrc' >> ~/.bashrc
source ~/.bashrc

##=================================================================================================
##
##  Install Cantera
##  
##=================================================================================================

echo "**Installing Cantera**"
echo " "

## Run Cantera install script
cd $(HEPH_CANT)
./cantera_install

echo " "
echo "**Cantera Install Complete**"
echo " "

##=================================================================================================
##
##  Install Utilities
##
##=================================================================================================

echo "**Installing Utilities**"
echo " "

## Run utilities install script
cd $(HEPH_UTIL)
./utils_install

echo " "
echo "**Utilities Installed**"
echo " "

##=================================================================================================
##
##  Install Modules
##
##=================================================================================================

echo "**Installing Modules**"
echo " "

## Run modules install script
cd $(HEPH_APP)
cd modules
./modules_installation

echo " "
echo "**Module Installed**"
echo " "

##=================================================================================================
##
##  Install Applications
##
##=================================================================================================

echo "**Installing Applications**"
echo " "

## Run applications install script
cd ../solvers
./solvers_installation

echo " "
echo "**Applications Installed**"
echo " "