#!/bin/bash
# HephaestusFoam environment setup

# Source OpenFOAM first (version you're basing it on)
source $FOAM_ETC/bashrc

# --- Versions ---
export CANTERA_VERSION="v2.6.0"          # or "2.6.1", "2.6.2"
export INSTALL_DIR="$HOME/cantera-$CANTERA_VERSION"

# --- C++ & Build Flags ---
export CXXFLAGS="-std=c++14"
export CC=gcc
export CXX=g++

# Add in the Cantera location
export CANT_HOME=/opt/cantera
export BUILD_DIR=$CANT_HOME

# Add Cantera-related paths
export CPATH=$HOME/hephaestusfoam/utilities/cantera/thermofluid/lnInclude:$HOME/hephaestusfoam/utilities/cantera/thermofluid:$CPATH
export LD_LIBRARY_PATH=$HOME/hephaestusfoam/utilities/cantera:$LD_LIBRARY_PATH

# Optional: point to your custom solvers/utilities
export PATH=$HOME/hephaestusfoam/utilities/cantera:$PATH

# Add in locations of different portions
export HEPH_APP=$HOME/hephaestusfoam/applications
export HEPH_UTIL=$HOME/hephaestusfoam/utilities
export HEPH_CANT=$HOME/hephaestusfoam/utilities/cantera
export HEPH_TUT=$HOME/hephaestusfoam/tutorials




