#!/bin/bash
    
#==================================================================================================
#
#  Download Cantera
#
#==================================================================================================

export INSTALL_DIR="$HOME/cantera"
mkdir -p $INSTALL_DIR && cd $INSTALL_DIR

# Clone the exact version
git clone https://github.com/Cantera/cantera.git
cd cantera
git fetch --tags
echo "Available Git tags for Cantera:"
git tag
echo "Trying to check out $CANTERA_VERSION"
git checkout "$CANTERA_VERSION" 
echo "Cantera version:"
git describe --tags
git pull
git status

#==================================================================================================
#
#  Configure SCONS and install
#
#==================================================================================================

mkdir -p $BUILD_DIR

# --- Configure Build ---
# Disable Python module if only C++ is needed (set yes if needed)
echo "Building Cantera with CXX Flags:"
echo $CXXFLAGS
echo "And CPATH:"
echo $CPATH
echo " "
scons build \
    prefix=$BUILD_DIR \
    optimize=y \
    debug=n \
    python_package=n \
    f90_interface=n \
    system_eigen=y \
    extra_inc_dirs=$TACC_EIGEN_DIR/include/eigen3 \
    boost_inc_dir=$TACC_BOOST_DIR/include


# --- Install ---
scons install > ~/hephaestusfoam/cantera_install.log

#==================================================================================================
#
#  Readout
#
#==================================================================================================

# --- Verification ---
strings $CANT_HOME/lib/libcantera.so | grep std=
# should show: -std=c++14

grep CANTERA_VERSION $CANT_HOME/include/cantera/base/config.h
# should show: 2.6.0

# --- Environment Setup ---
echo "
# ===== Cantera $CANTERA_VERSION =====
export CANTERA_ROOT=$INSTALL_DIR
export PATH=\$CANTERA_ROOT/bin:\$PATH
export LD_LIBRARY_PATH=\$CANTERA_ROOT/lib/x86_64-linux-gnu:\$CANTERA_ROOT/lib:\$LD_LIBRARY_PATH
export PYTHONPATH=\$CANTERA_ROOT/lib/python3/site-packages:\$PYTHONPATH
" >> ~/.bashrc

echo "? Cantera $CANTERA_VERSION installed to $INSTALL_DIR"

rm -rf $INSTALL_DIR
