#!/bin/bash
    
#==================================================================================================
#
#  Download Cantera
#
#==================================================================================================

export INSTALL_DIR="$HOME/cantera"
mkdir -p $INSTALL_DIR && cd $INSTALL_DIR

# Clone the exact version
git clone https://github.com/Cantera/cantera.git
cd cantera
git fetch --tags
##echo "Available Git tags for Cantera:"
##git tag
echo "Trying to check out $CANTERA_VERSION"
git checkout "$CANTERA_VERSION" 
echo "Cantera version:"
git describe --tags
git pull
git status

#==================================================================================================
#
#  Setup Anaconda for a Cantera environement
#
#==================================================================================================

echo " "

# Check to see if conda is even installed
if ! command -v conda >/dev/null 2>&1; then
    echo " "
    echo "**Cricial error found**"
    echo " "
    echo "Conda not found. Please install Miniconda"
    echo " "
fi

#  Set the environment name
ENV_NAME="cantera"

# Enable the 'conda' command in non-interactive shells
source "$(conda info --base)/etc/profile.d/conda.sh"

# Check if the environment exists
if ! conda env list | awk '{print $1}' | grep -qx "$ENV_NAME"; then
    echo "Creating Conda environment: $ENV_NAME"

    conda create -y -n cantera \
      python=3.10 \
      scons \
      "setuptools<69" \
      numpy \
      cython \
      ruamel.yaml \
      pytest \
      -c conda-forge
else
    echo "Using existing Conda environment: $ENV_NAME"

    conda install -y -n "$ENV_NAME" \
        scons \
        setuptools=68.2.2 \
        numpy \
        cython \
        ruamel.yaml \
        pytest \
        -c conda-forge
fi

# Activate it
conda activate "$ENV_NAME"

# Install Eigen into environment
conda install -c conda-forge eigen

# Verify scons
echo " "
echo "SCONS verification: "
which scons
scons --version
python -c "import pkg_resources; print(pkg_resources.__file__)"

#==================================================================================================
#
#  Configure SCONS and install
#
#==================================================================================================

export BUILD_DIR="$CANT_HOME"
mkdir -p $BUILD_DIR

# --- Configure Build ---
# Disable Python module if only C++ is needed (set yes if needed)
echo "Building Cantera with CXX Flags:"
echo $CXXFLAGS
echo "And CPATH:"
echo $CPATH
echo " "
scons build \
    prefix=$BUILD_DIR \
    optimize=y \
    debug=n \
    python_package=n \
    f90_interface=n \
    system_eigen=n > ~/HephaestusFOAM/utilities/cantera/cantera_build.log


# --- Install ---
echo " "
echo "Installing Cantera"
scons install > ~/HephaestusFOAM/utilities/cantera/cantera_install.log
echo " "

#==================================================================================================
#
#  Readout
#
#==================================================================================================

# --- Verification ---
strings $CANT_HOME/lib/libcantera.so | grep std=
# should show: -std=c++14

grep CANTERA_VERSION $CANT_HOME/include/cantera/base/config.h
# should show: 2.6.0

echo "Cantera $CANTERA_VERSION installed to $BUILD_DIR"

rm -rf $INSTALL_DIR
