#!/bin/bash
set -e

echo "Beginning installation of Cantera package"
export hephaestus_utilsDir="$PWD"

#==================================================================================================
#
#  Create dynamic links for included thermodynamic files
#
#==================================================================================================

ln -sf "$hephaestus_utilsDir/include"/* cantera/thermofluid/lnInclude
# ln -sf include/* cantera/factory
ln -sf "$hephaestus_utilsDir/cantera/thermofluid/rhoThermo"/* cantera/thermofluid/lnInclude
ln -sf "$hephaestus_utilsDir/cantera/thermofluid/psiThermo"/* cantera/thermofluid/lnInclude
ln -sf "$hephaestus_utilsDir/cantera/thermofluid/rhoMulticomponentThermo"/* cantera/thermofluid/lnInclude
ln -sf "$hephaestus_utilsDir/cantera/thermofluid/psiMulticomponentThermo"/* cantera/thermofluid/lnInclude
ln -sf "$hephaestus_utilsDir/cantera/thermofluid/multicomponent/fluidMulticomponentThermo"/* cantera/thermofluid/lnInclude
ln -sf "$hephaestus_utilsDir/cantera/thermofluid/mixtures/canteraMulticomponentMixture"/* cantera/thermofluid/lnInclude
ln -sf "$hephaestus_utilsDir/cantera/thermofluid/factory"/* cantera/thermofluid/lnInclude

#==================================================================================================
#
#  Create dynamic links for included chemistry files
#
#==================================================================================================

ln -sf "$hephaestus_utilsDir/cantera/thermochemistry/chemistryModel"/* cantera/thermochemistry/lnInclude
ln -sf "$hephaestus_utilsDir/cantera/thermochemistry/chemistrySolver"/* cantera/thermochemistry/lnInclude

#==================================================================================================
#
#  Install Cantera Thermofluid Package
#
#==================================================================================================

export start_dir=$PWD

echo "Changing to cantera directory: $start_dir/cantera/thermofluid"
cd "$start_dir/cantera/thermofluid"

echo "Compiling thermo package with wmake..."
wmake > cantera_make.log 2>&1

echo "Compilation complete. Log saved to cantera_make.log"

#==================================================================================================
#
#  Install Cantera Thermochemistry Package
#
#==================================================================================================

cd ../thermochemistry

echo "Compiling chemistry package with wmake..."
wmake > cantera_make.log 2>&1

#==================================================================================================
#
#  Move tables over
#
#==================================================================================================

cd ../tables

cp basicChemistryModel $FOAM_ETC/codeTemplates/dynamicCode
cp fluidMulticomponentThermo $FOAM_ETC/codeTemplates/dynamicCode
