#!/bin/bash

echo " "
echo "**Installing Discretization Schemes**"
echo " "

export disc_utilsDir="$PWD"

#==================================================================================================
#
#  Create dynamic links for RK Tableau
#
#==================================================================================================

echo "Creating dynamic links..."
ln -sf "$disc_utilsDir/RKTimeIntegration"/* lnInclude

#==================================================================================================
#
#  Install the RK Tableau
#
#==================================================================================================

cd RKTimeIntegration

echo "Building RK Tableau..."
wmake libso > rkTableau_make.log 2>&1
