#!/bin/bash
set -e

echo "Beginning installation of HephaestusFOAM modules"

#==================================================================================================
#
#  Install hephaestusGas
#
#==================================================================================================

echo " "
echo "Installing gasHephaestus"
echo " "

cd gasHephaestus
wmake > build.log
cd ../

#==================================================================================================
#
#  Install waveHephaestus
#
#==================================================================================================

echo " "
echo "Installing waveHephaestus"
echo " "

cd waveHephaestus
wmake > build.log
cd ../

